config/routes.rb
Rails.application.routes.draw do
  
  root 'welcomes#new'
  resources :managers
  resources :hospitals do
    resources :users do
      resources :babies do
        member do
          post :send_email
        end
        resources :healths
      end
    end
  end

  get '/download_data', to: 'welcomes#download_data'

  resources :babies do 
    resources :healths do
      collection do
        get :weight
        get :height
      end
    end
    resources :vitamin_as, only: [:new, :create]
    resources :baby_infant_feedings
    resources :baby_cares

    collection do
      get :get_report_data
    end
  end
  resources :baby_vitamins, only: [:new, :create]
  resources :baby_vaccinations 
  resources :fathers
  resources :risk_factors
  resources :vaccinations
  resources :infant_feeding_labels 
  resources :care_labels 
  resources :mothers
  resource :admin, only: [:new]
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health.rb
require 'csv'
class Health < ApplicationRecord
  DAYS_IN_MONTH  = [nil, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

  belongs_to :baby, inverse_of: :healths
  validates :weight, presence: true
  validates :height, presence: true
  before_save :calculate_age

  def calculate_age
    return if baby.blank?
    borrowed_month = false

    current_date = Time.new
    birth_date = Time.parse(baby.date_of_birth)

    # Get days for this year
    if current_date.to_date.leap?
      DAYS_IN_MONTH[2] = 29
    end

    day   = current_date.day - birth_date.day
    month = current_date.month - birth_date.month
    year  = current_date.year - birth_date.year

    if day < 0
      # subtract month, get positive # for day
      day = DAYS_IN_MONTH[birth_date.month] - birth_date.day + current_date.day
      month -= 1
      borrowed_month = true
    end

    if month < 0
    # subtract year, get positive # for month
      month = 12 - birth_date.month + current_date.month
      if borrowed_month == true
        month -= 1
      end
      year -= 1
    end

    if year < 0
      year, month, day = 0, 0, 0
    end

    

    self.age = (year*12)+ month + (day>20 ? 1 : 0)
    self.baby.update(age: self.age)
  end
  
    def self.import_data(objects)
      CSV.generate do |csv|
        if objects.present?
          objects.each do |key, val|
            csv << ["key", key]
            csv << ["value", val]
          end
        else
          csv << ["You don't have any Data to show"]
        end
      end
    end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  include HealthsHelper
  before_action :authenticate_user!
  before_action :set_baby

  def height
    height_age_chart_data(@baby)
    respond_to do |format|
      format.html
      format.csv { send_data Health.import_data(@data), filename: "BabyHeight-#{Date.today}.csv"}
    end
  end

  def weight
    weight_age_chart_data(@baby)
    respond_to do |format|
      format.html
      format.csv { send_data Health.import_data(@weight_data), filename: "BabyWeight-#{Date.today}.csv"}
    end
  end

  def new
    @health = @baby.healths.new
  end

  def create
    @health = @baby.healths.new(healths_params)
     if @health.save
      flash[:success] = "Added successfully."
      redirect_to edit_hospital_user_baby_path(@baby.hospital_id, @baby.user_id, @baby.id)
    else
      flash[:alert] = @health.errors.full_messages.join(' ,')
      render 'new'
    end
  end 

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:baby_id])
    end

    def healths_params
      params.require(:health).permit(:age, :height, :weight, :date)
    end
end

app/helpers/healths_helper.rb
module HealthsHelper
  LABEL =  (0..60).collect {|x| x }
  
  def height_age_chart_data(baby)
    @data = {
      labels: LABEL,
        datasets: [
        {
          radius: 0,
          tension: 0.6,
          label: "Severe stunted",
          border_color: "#a3e1d4",
          background_color: "rgba(0,0,0,0.0)",
          data: Baby::SEVERE_STUNTED_HEIGHT
          
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Moderate stunted",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#1AB394',
          data: Baby::MODERATE_STUNTED_HEIGHT
          
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Normal",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#9CC3DA',
          data: Baby::NORMAL 
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Normal 2",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#B5B8CF',
          data: Baby::NORMAL2 
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Possible very tall",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#9fe3f2',
          data: Baby::POSSIBLE_VERY_TALL
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Capture Data",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#000000',
          data: (0..60).collect{ |age| baby.healths.find_by(age: age).try(:height) ? baby.healths.find_by(age: age).height : 0}
        }
      ]
    }
 end

  def weight_age_chart_data(baby)
    @weight_data = {
      labels: LABEL,
        datasets: [
        {
          radius: 0,
          tension: 0.6,
          label: "Severe underweight",
          border_color: "#a3e1d4",
          background_color: "rgba(0,0,0,0.0)",
          data:  Baby::SEVERE_UNDER_WEIGHT
          
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Moderate underweight",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#1AB394',
          data:  Baby::MODERATE_UNDER_WEIGHT
          
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Normal",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#9CC3DA',
          data: Baby::NORMAL_WEIGHT 
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Possible overweight",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#B5B8CF',
          data: Baby::POSSIBLE_OVERWEIGHT
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Check weight - for height",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#9fe3f2',
          data: Baby::CHECK_WEIGHT_FOR_HEIGHT
        },
        {
          radius: 0,
          tension: 0.6,
          label: "Capture Data",
          background_color: "rgba(0,0,0,0.0)",
          border_color: '#000000',
          data:  (0..60).collect{ |age| baby.healths.find_by(age: age).try(:weight) ? baby.healths.find_by(age: age).weight : 0}
        }
      ]
    }
  end
end
      

app/views/healths/_form.html.haml
= form_with(model: health, local: true) do |form|
  - if @health.errors.any?
    #error_explanation
      %h2
        = pluralize(health.errors.count, "error")
        prohibited this health from being saved:
      %ul
        - @health.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/healths/edit.html.haml
%h1 Editing Health
= render 'form', health: @health
= link_to 'Show', @health
|
= link_to 'Back', healths_path

app/views/healths/height.html.haml
.pull-right
  - if current_user.admin?
    = link_to "Back", babies_path, class: "btn btn-success"
.container
  %h1 Baby Height data Chart
  = link_to "Download Data", height_baby_healths_path(@baby, format: "csv")
  %br
  .index-container
    .col-md-12
      = chartjs_line_chart(@data,{title: {display:true, position: "bottom", text: "Age in Month"}, scales: {xAxes: [{gridLines: {display:true}}], yAxes: [{scaleLabel: {display: true,labelString: 'Height in cm'},gridLines: {display:true}, ticks: {beginAtZero:true}}]}, maintainAspectRatio: false, height: 500}) 

app/views/healths/new.html.haml
.pull-right
  = link_to "Back",  edit_hospital_user_baby_path(@baby.hospital, @baby.user, @baby), class: "btn btn-success"
.container
  .signup-container
    %h1 Add Health Info
    %br
    = bootstrap_form_for @health, url: hospital_user_baby_healths_path(@baby.hospital, @baby.user, @baby),  local: true do |form|
      = form.text_field :height,  placeholder: "Enter height"
        
      = form.text_field :weight,  placeholder: "Enter weight"

      = form.date_field :date,  placeholder: "Enter date"

      = form.submit "submit", class: "btn btn-lg btn-success"

app/views/healths/weight.html.haml
.pull-right
  - if current_user.admin?
    = link_to "Back", babies_path, class: "btn btn-success"
.container
  %h1 Baby Weight data Chart
  = link_to "Download Data", weight_baby_healths_path(@baby, format: "csv")
  %br
  .index-container
    .col-md-12
      = chartjs_line_chart(@weight_data,{title: {display:true, position: "bottom", text: "Age in Month"}, scales: {xAxes: [{gridLines: {display:true}}], yAxes: [{scaleLabel: {display: true,labelString: 'Weight in kg'},gridLines: {display:true}, ticks: {beginAtZero:true}}]}, maintainAspectRatio: false, height: 500}) 