config/routes.rb
Rails.application.routes.draw do
  
  root 'welcomes#new'
  resources :managers
  resources :hospitals do
    resources :users do
      resources :babies do
        member do
          post :send_email
        end
        resources :healths
      end
    end
  end

  get '/download_data', to: 'welcomes#download_data'

  resources :babies do 
    resources :healths do
      collection do
        get :weight
        get :height
      end
    end
    resources :vitamin_as, only: [:new, :create]
    resources :baby_infant_feedings
    resources :baby_cares

    collection do
      get :get_report_data
    end
  end
  resources :baby_vitamins, only: [:new, :create]
  resources :baby_vaccinations 
  resources :fathers
  resources :risk_factors
  resources :vaccinations
  resources :infant_feeding_labels 
  resources :care_labels 
  resources :mothers
  resource :admin, only: [:new]
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vaccination.rb
require 'csv'
class Vaccination < ApplicationRecord
  has_many :baby_vaccinations, dependent: :destroy
  has_many :babies, through: :baby_vaccinations
  validates :age, presence: true
  validates :title, presence: true
  validates :batch_number, presence: true
  validates :dose_number, presence: true


  def self.import_vaccinations(vaccinations)
    CSV.generate do |csv|
      if vaccinations.present?
        vaccinations.each do |vaccination|
          csv << ["VaccinationId", vaccination.id]
          csv << ["Title", vaccination.title]
          csv << ["Age", vaccination.age]
          csv << ["BatchNumber", vaccination.batch_number]
          csv << ["DoseNumber", vaccination.dose_number]
          csv << ["Description", vaccination.description]
          csv << []
        end
      else
        csv << ["You don't have any Vaccinations"]
      end
    end
  end
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  include VaccinationsHelper
  before_action :authenticate_user!
  before_action :set_vaccination, only: [:show, :edit, :update, :destroy]
  

  def index
   @vaccinations = Vaccination.all if current_user.admin?
    vaccination_bar_chart_under23_age_data
    vaccination_bar_chart_over23_age_data
    respond_to do |format|
      format.html
      format.csv { send_data Vaccination.import_vaccinations(@vaccinations), filename: "Vaccinations-#{Date.today}.csv"}
    end
  end

  def new
    @vaccination = Vaccination.new
  end

  def create
    if current_user.admin?
      @vaccination = Vaccination.new(vaccination_params)
      if @vaccination.save
        flash[:success] = "Added successfully."
        redirect_to  vaccinations_path
      else
        flash[:alert] = "Please fill required field."
        render 'new'
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @vaccination.update(vaccination_params)
      flash[:alert] = "Update Successfully." 
      redirect_to vaccinations_path
    else
      flash[:alert] = @vaccination.errors.full_messages.join(' ,')
      render 'edit'
    end
  end

  def destroy
    flash[:alert] = "Destroy Successfully." if @vaccination.destroy
    redirect_to vaccinations_path
  end

  private
    
    def set_vaccination
      @vaccination = Vaccination.find(params[:id])
    end

    def vaccination_params
      params.require(:vaccination).permit(:title, :age, :description, :dose_number, :batch_number)
    end
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper

  def vaccination_bar_chart_under23_age_data
    @vaccination_data = {
      labels: Vaccination.all.collect(&:title),
      datasets: [
        {
          background_color: ["#a3e1d4", "#B5B8CF", "#a3e1d4", "#B5B8CF"],
          data:  Vaccination.all.collect{|v| v.babies.where(hospital_id: current_user.hospitals.pluck(:id)).where("babies.age >= ? and babies.age <= ?", 0, 23).count}
        }
      ]
    }
  end


  def vaccination_bar_chart_over23_age_data
    @vaccination = {
      labels: Vaccination.all.collect(&:title),
      datasets: [
        {
          background_color: ["#a3e1d4", "#B5B8CF", "#a3e1d4", "#B5B8CF"],
          data:  Vaccination.all.collect{|v| v.babies.where(hospital_id: current_user.hospitals.pluck(:id)).where("babies.age >= ? and babies.age <= ?", 24, 60).count}
        }
      ]
    }
  end
end

app/views/vaccinations/edit.html.haml
.pull-right
  = link_to "Back", risk_factors_path, class: "btn btn-success"
.container
  .signup-container
    %h1 Edit Vaccination
    %br
    = bootstrap_form_for  @vaccination, url: vaccination_path(@vaccination),  local: true do |form|
      .row
        .col-md-6
          = form.text_field :age
      %br
      .row  
        .col-md-10
          = form.text_field :batch_number,  placeholder: "enter batch number"
      %br
      .row  
        .col-md-10
          = form.text_field :dose_number,  placeholder: "enter dose number"
      %br
      .row  
        .col-md-10
          = form.text_field :title,  placeholder: "enter vaccination title"
      %br 
      .row
        .col-md-10 
          = form.text_field :description,  placeholder: "Enter type of course"
      %br  
      .row
        .col-md-12
          = form.submit "Update", class: "btn btn-primary"

app/views/vaccinations/index.html.haml
.pull-right
  - if current_user.admin?
    = link_to "Add vaccination", new_vaccination_path, class: "btn btn-success"    
.container
  .container.index-container
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2 Vaccinations List
        .ibox-content
          %table.table.table-bordered
            %thead
              %tr
                %th Age(month)
                %th Title
                %th Course Description
                %th Action
            %tbody
              - @vaccinations.each do |vaccination|
                %tr
                  %td= vaccination.age
                  %td= vaccination.title
                  %td= vaccination.description
                  %td
                    = link_to "",  edit_vaccination_path(vaccination), class: "btn btn-default glyphicon glyphicon-edit"
                    = link_to "", vaccination_path(vaccination), method: :delete,data: { confirm: 'Are you sure?' }, class: "btn btn-default glyphicon glyphicon-trash"       

          
                 
 

app/views/vaccinations/new.html.haml
.pull-right
  = link_to "Back", vaccinations_path, class: "btn btn-success"
.container
  .signup-container
    %h1 Add New Vaccination
    %br
    = bootstrap_form_for  @vaccination, url: vaccinations_path,  local: true do |form|
      .row
        .col-md-6
          = form.text_field :age
      %br
      .row  
        .col-md-10
          = form.text_field :batch_number,  placeholder: "enter batch number"
      %br
      .row  
        .col-md-10
          = form.text_field :dose_number,  placeholder: "enter dose number"
      %br
      .row  
        .col-md-10
          = form.text_field :title,  placeholder: "enter vaccination title"
      %br 
      .row
        .col-md-10 
          = form.text_field :description,  placeholder: "enter type of course"
      %br  
      .row
        .col-md-12
          = form.submit "Save", class: "btn btn-primary"