config/routes.rb
Rails.application.routes.draw do
  
  root 'welcomes#new'
  resources :managers
  resources :hospitals do
    resources :users do
      resources :babies do
        member do
          post :send_email
        end
        resources :healths
      end
    end
  end

  get '/download_data', to: 'welcomes#download_data'

  resources :babies do 
    resources :healths do
      collection do
        get :weight
        get :height
      end
    end
    resources :vitamin_as, only: [:new, :create]
    resources :baby_infant_feedings
    resources :baby_cares

    collection do
      get :get_report_data
    end
  end
  resources :baby_vitamins, only: [:new, :create]
  resources :baby_vaccinations 
  resources :fathers
  resources :risk_factors
  resources :vaccinations
  resources :infant_feeding_labels 
  resources :care_labels 
  resources :mothers
  resource :admin, only: [:new]
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_hospitals
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  def index
    @users = User.where(role: "manager", hospital_id: current_user.hospitals.ids) if current_user.admin?
    authorize @users
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    if current_user.admin?
      @user = User.new(user_params)
      @user.role = "manager"
      if @user.save
        flash[:success] = "created successfully."
        redirect_to  managers_path
      else
        flash[:alert] = "Please fill required field."
        render 'new'
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:alert] = "Update Successfully." 
      redirect_to managers_path
    else
      flash[:alert] = @user.errors.full_messages.join(' ,')
      render 'edit'
    end
  end

  def destroy
    flash[:alert] = "Destroy Successfully." if @user.destroy
    redirect_to managers_path
  end

  private
    
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    def load_hospitals
      @hospitals = current_user.hospitals.collect{|f| [f.name, f.id]}	
    end

    def user_params
      params.require(:user).permit(:hospital_id, :first_name, :last_name, :email, :password)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/edit.html.erb
<div class="pull-right">
  <%= link_to "Back", managers_path, class: "btn btn-success" %>
</div>

<div class="container">
  <div class="container signup-container">
    <div class="col-md-12">
      <h1>Edit Manager Account</h1>
    </div>  
    <br>
      <%= bootstrap_form_for @user, url: manager_path, local: true do |form| %>
        <div class="row">  
          <div class="col-md-6">
            <%= form.text_field :first_name,  placeholder:"Enter First Name",  icon: "user" %>
          </div>
          <div class="col-md-6">
            <%= form.text_field :last_name, placeholder: "Enter last Name",  icon: "user" %>
          </div>
        </div>
        <%= form.select :hospital_id, @hospitals, :prompt => 'Select hospital id' %>
        
        <%= form.email_field :email, placeholder: "User email" %>
        <%= form.password_field :password, placeholder: "password" %>
        <%= form.submit "Update Account", class: "btn btn-info btn-lg" %>
      <% end  %>         
  </div> 
</div>      
     

app/views/managers/index.html.erb
<div class="pull-right">
    <%= link_to "New manager", new_manager_path, class: "btn btn-success" %>
</div>
  <div class="container">
    <div class="container index-container">
      <div class="col-md-12">
        <h1>Manager List</h1>
      </div>
      <br>
    <div class="col-md-12">
      <table class="table table-stripped">
        <thead>  
          <tr>
            <th>Id</th>
            <th>Hospital Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Action</th>
            
          </tr>
        </thead> 
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.hospital_id %></td> 
              <td><%= user.first_name %></td> 
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>      
              <td ><%= link_to '',  edit_manager_path(user), class: "btn btn-default glyphicon glyphicon-edit" %>
              <%= link_to'',   manager_path(user), class: "btn btn-default glyphicon glyphicon-eye-open" %>
              <%= link_to '',  manager_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-default glyphicon glyphicon-trash" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>    
  </div>
</div>

app/views/managers/new.html.erb
<div class="pull-right">
  <%= link_to "Back", managers_path, class: "btn btn-success" %>
</div>

<div class="container">
  <div class="signup-container">
    <div class="col-md-12">
      <h1>SignUp Manager Account</h1>
    </div> 
    <br>          
    <%= bootstrap_form_for @user, url: managers_path, local: true do |form| %>
    <div class="row">  
      <div class="col-md-6">
        <%= form.text_field :first_name,  placeholder:"Enter First Name",  icon: "user" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :last_name, placeholder: "Enter last Name",  icon: "user" %>
      </div>
    </div>
      <%= form.select :hospital_id, @hospitals, :prompt => 'Select hospital id' %>
      
      <%= form.email_field :email, placeholder: "User email" %>
      <%= form.password_field :password, placeholder: "password" %>
      <%= form.submit "Create Account", class: "btn btn-info btn-lg" %>
    <% end  %>         
  </div> 
</div>      
     

app/views/managers/show.html.erb
<div class="pull-right">
  <%= link_to "Back", managers_path, class: "btn btn-success" %>
</div>
<div class="container">
  <div class="container table-container">
    <div class="col-md-12">
      <h1>Information of Manager</h1>
    </div>   
    <br>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>Hospital Id</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.id %></td>
          <td><%= @user.hospital_id %></td>
          <td><%= @user.first_name %></td>
          <td><%= @user.last_name %></td>
          <td><%= @user.email %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>