config/routes.rb
Rails.application.routes.draw do
  
  root 'welcomes#new'
  resources :managers
  resources :hospitals do
    resources :users do
      resources :babies do
        member do
          post :send_email
        end
        resources :healths
      end
    end
  end

  get '/download_data', to: 'welcomes#download_data'

  resources :babies do 
    resources :healths do
      collection do
        get :weight
        get :height
      end
    end
    resources :vitamin_as, only: [:new, :create]
    resources :baby_infant_feedings
    resources :baby_cares

    collection do
      get :get_report_data
    end
  end
  resources :baby_vitamins, only: [:new, :create]
  resources :baby_vaccinations 
  resources :fathers
  resources :risk_factors
  resources :vaccinations
  resources :infant_feeding_labels 
  resources :care_labels 
  resources :mothers
  resource :admin, only: [:new]
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/baby.rb
require 'csv'
class Baby < ApplicationRecord

  SEVERE_STUNTED_HEIGHT   =  [43,48,51,52.5,54.5,57.5,59,60.5,62,63,64,65,66,67,68,69,70,71,72,73,73.5,75,76,76.5,77,77.5,78,78.5,79.5,80,80.5,81,82,82.5,83,83.5,84,84.5,85,85.5,86,86.5,87,87.5,88,88.5,89,89,90,90.5,91,91.5,92,92.5,93,93.5,94,94,94.5,95]
  MODERATE_STUNTED_HEIGHT =  [46,50,53,55.5,58,59.5,61,62.5,64,65,66.5,67.5,67,70,71,72,73,74,75,76,76.5,77.5,78,79,80,80,80.5,81.5,82,83,83.5,84,85,85.5,86,86.5,87,88,88.5,89,89.5,90,90.5,91,92,92.5,93,93.5,94,94.5,95,95.5,96,96.5,97,97.5,98,98.5,99,99,99.5]
  NORMAL                  =  [49,54,57,58.5,62,64,65.5,67,68.5,70,70,72.5,74,75,76,77,78,79,80,80.5,82.5,83,84,85,86,86,87,88,88.5,89.5,90,91,92,92.5,93,94,94.5,95,96,96.5,97,98,98.5,99,100,100.5,101,101.5,102,103,103.5,104,104.5,105,105.5,106,106.5,107,108,108.5,109]
  NORMAL2                 =  [53,58,61,64,66.5,68.5,70,72,73.5,75,76,77.5,79,80,81.5,83,84,85,86,86.5,88.5,89.5,91,92,93,93,94,95,96,96.5,97.5,98.5,99,100,101,101.5,102.5,103,104,104.5,105.5,106,106.5,107.5,108,109,110,110.5,111,111.5,112,113,113.5,114,115,115.5,116,117,117.5,118,118.5] 
  POSSIBLE_VERY_TALL      =  [55,60,63,66,68.5,70.5,72.5,74,75.5,77,79,80,81.5,83,84.5,85.5,87,88,88.5,90.5,91.5,92.5,94,95,96,96,97.5,98.5,99,100,101,102,103,103.5,104.5,105.5,106,107,108,108.5,109.5,110,111,115.5,112.5,113,114,114.5,115,116,116.5,117.5,118,119,119.5,120,120.5,121,122,122.5,123]
  SEVERE_UNDER_WEIGHT     =  [2,2.6,3.5,4,4.4,4.8,5,5.4,5.6,5.8,6,6.2,6.3,6.4,6.6,6.8,6.9,7,7.2,7.4,7.6,7.7,7.8,8,8.1,8.2,8.4,8.5,8.6,8.8,8.9,9,9.2,9.3,9.4,9.6,9.7,9.8,9.9,10,10.1,10.2,10.3,10.4,10.5,10.6,10.7,10.8,10.9,11,11.1,11.2,11.3,11.4,11.5,11.6,11.8,11.9,12,12,12.1]
  MODERATE_UNDER_WEIGHT   =  [2.4,3.2,4,4.6,5,5.4,5.8,6,6.2,6.4,6.6,6.8,7,7.2,7.4,7.6,7.8,8.9,8.1,8.3,8.4,8.6,8.8,8.9,9.1,9.2,9.4,9.6,9.7,9.8,10,10.1,10.2,10.4,10.6,10.7,10.8,11,11.1,11.2,11.4,11.5,11.6,11.8,11.9,12,12.1,12.2,12.4,12.5,12.6,12.7,12.8,12.9,13,13.2,13.3,13.4,13.6,13.6,13.7]
  NORMAL_WEIGHT           =  [3.2,4.2,5,5.8,6.4,6.8,7.2,7.6,7.8,8.2,8.4,8.6,8.8,9,9.2,9.4,9.8,10,10.2,10.4,10.6,10.8,11,11.2,11.4,11.4,11.8,12,12.2,12.4,12.6,12.8,13,13.2,13.4,13.6,13.8,14,14.1,14.2,14.3,14.6,14.8,15,15.2,15.4,15.6,15.8,16,16.2,16.4,16.5,16.8,16.9,17.1,17.2,17.4,17.6,17.8,17.9,18]
  POSSIBLE_OVERWEIGHT     =  [4.2,5.4,6.6,7.6,8.2,8.8,9.4,9.8,10.2,10.6,10.9,11.2,11.4,11.8,12,12.4,12.6,12.9,13.2,13.4,13.8,14,14.2,14.6,14.8,15,15.4,15.6,16,16.2,16.4,16.8,17.2,17.3,17.6,17.8,18,18.4,18.6,19,19.2,19.4,19.8,20,20.2,20.6,20.8,21.1,21.4,21.6,22,22.2,22.4,22.8,23,23.2,23.8,24,24.2,24.4,24.8]
  CHECK_WEIGHT_FOR_HEIGHT =  [4.8,6.2,7.6,8.6,9.4,10,10.7,11,11.6,12,12.2,12.8,13,13.4,13.8,14.2,14.4,14.8,15.2,15.4,15.6,16,16.2,16.6,17,17.2,17.6,18,18.2,18.6,19,19.2,19.6,19.9,20.2,20.4,20.8,21.2,21.4,22,22.2,22.4,22.8,23.2,23.6,24,24.4,24.6,25,25.4,25.8,26,26.4,26.8,27.2,27.4,27.8,28.2,28.6,29,29.2]

  has_many :healths, inverse_of: :baby
  has_many :baby_risk_factors, inverse_of: :baby

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :hospital
  belongs_to :user,  optional: true
  has_one :mother
  has_one :father
  has_many :baby_vaccinations
  has_many :vitamin_as
  has_many :risk_factors, through: :baby_risk_factors
  has_many :baby_infant_feedings
  has_many :baby_cares

  validates :first_name, presence: true
  validates :place_of_birth, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  validates :sex, presence: true
  validates :head_circumference, presence: true
  validates :agpr_score, presence: true
  validates :mode_of_delivery, presence: true
  validates :duration_of_labour, presence: true
  accepts_nested_attributes_for :baby_cares, allow_destroy: true, reject_if: proc {|attributes| (attributes.has_key?("care_month_id") && attributes["care_month_id"].to_i == 0) || (attributes.has_key?("description") && attributes["description"].blank?) || (attributes.has_key?("comment") && attributes["comment"].blank?)}  
  accepts_nested_attributes_for :baby_infant_feedings, allow_destroy: true, reject_if: proc {|attributes| attributes['infant_feeding_label_id'].to_i == 0 || (attributes.has_key?("infant_feeding_month_id") && attributes["infant_feeding_month_id"].to_i == 0) || (attributes.has_key?("description") && attributes["description"].blank?)}
  accepts_nested_attributes_for :father, allow_destroy: true
  accepts_nested_attributes_for :mother, allow_destroy: true
  accepts_nested_attributes_for :healths, allow_destroy: true
  accepts_nested_attributes_for :baby_risk_factors, allow_destroy: true, reject_if: proc { |attributes| attributes['risk_factor_id'].to_i == 0 }
  
  has_attached_file :avatar
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
  
  scope :male_babies, -> { where(sex: "male") }
  scope :female_babies, -> { where(sex: "female") }

  class << self
    def get_result params 
      case params[:filter]
      when "Moderate Stunted Height"
        Baby.joins(:healths).where("date_of_birth = ? AND healths.height IN (?)", params["date"], Baby::MODERATE_STUNTED_HEIGHT)
      when "Severe Stunted Height"
        Baby.joins(:healths).where("date_of_birth = ? AND healths.height IN (?)", params["date"], Baby::SEVERE_STUNTED_HEIGHT)
      when "Moderate Under Weight"
        Baby.joins(:healths).where("date_of_birth = ? AND healths.weight IN (?)", params["date"], Baby::MODERATE_UNDER_WEIGHT)
      when "Severe Under Weight"
        Baby.joins(:healths).where("date_of_birth = ? AND healths.weight IN (?)", params["date"], Baby::SEVERE_UNDER_WEIGHT)
      end
    end


    def get_data
      total_babies = Baby.count
      severe_stunted_height_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::SEVERE_STUNTED_HEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }.sort{|a,b| a[:x] <=> b[:x] }
      
     severe_under_weight_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::SEVERE_UNDER_WEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      moderate_under_weight_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::MODERATE_UNDER_WEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      normal_weight_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::NORMAL_WEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      possible_overweight_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::POSSIBLE_OVERWEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      weight_for_height_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::CHECK_WEIGHT_FOR_HEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      moderate_stunted_height_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::MODERATE_STUNTED_HEIGHT).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      normal_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::NORMAL).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }.flatten

      normal_2_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::NORMAL2).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      possible_very_tall_babies = Baby.joins(:healths).where("healths.height IN (?)", Baby::POSSIBLE_VERY_TALL).group_by{|a| a.age_in_months}.map{|k,v| {x: k, y: ((v.size.to_i/total_babies.to_f)*100).round(2)}}.sort{|a,b| a[:x] <=> b[:x] }

      OpenStruct.new(severe_stunted_height: severe_stunted_height_babies,severe_under_weight:severe_under_weight_babies, moderate_under_weight: moderate_under_weight_babies,  normal_weight: normal_weight_babies, possible_overweight: possible_overweight_babies, weight_for_height: weight_for_height_babies,moderate_stunted_height: moderate_stunted_height_babies, normal: normal_babies, normal_2: normal_2_babies, possible_very_tall: possible_very_tall_babies )
    end

  
    def import
      data = get_data
      CSV.generate do |csv|
        csv << ["BABIES DATA"]
        csv << [""]
        csv << [""]

        csv << ["SEVERE STUNTED HEIGHT"]
        csv << ["Number of Babies", data.severe_stunted_height.size]
        csv << ["Percentage ", data.severe_stunted_height.join(",")]
        csv << [""]

        csv << ["SEVERE UNDER WEIGHT"]
        csv << ["Number of Babies", data.severe_under_weight.size]
        csv << ["Percentage ", data.severe_under_weight.join(",")]
        csv << [""]

        csv << ["MODERATE UNDER WEIGHT"]
        csv << ["Number of Babies", data.moderate_under_weight.size]
        csv << ["Percentage ", data.moderate_under_weight.join(",")]
        csv << [""]

        csv << ["NORMAL WEIGHT"]
        csv << ["Number of Babies", data.normal_weight.size]
        csv << ["Percentage ", data.normal_weight.join(",")]
        csv << [""]

        csv << ["POSSIBLE OVERWEIGHT"]
        csv << ["Number of Babies", data.possible_overweight.size]
        csv << ["Percentage ", data.possible_overweight.join(",")]
        csv << [""]

        csv << ["WEIGHT FOR HEIGHT"]
        csv << ["Number of Babies", data.weight_for_height.size]
        csv << ["Percentage ", data.weight_for_height.join(",")]

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_user, if: -> { current_user.present? && (current_user.nurse? || current_user.manager?)}, except: [:get_report_data]
  before_action :set_baby, only: [:show, :edit, :update, :destroy, :send_email]

  def index
    @babies = if current_user.nurse?
      @user.babies 
    elsif current_user.admin?
      Baby.where(hospital_id: current_user.hospital_ids)
    else
      Baby.where(hospital_id: current_user.hospital_id)
    end
    respond_to do |format|
      format.html
      format.csv { send_data current_user.import(@babies), filename: "Babies-#{Date.today}.csv"} 
    end
    authorize @babies
  end

  def new
    @baby = @user.babies.build
    RiskFactor.all.each { |risk_factor| @baby.baby_risk_factors.build(risk_factor_id: risk_factor.id) }
    authorize @baby
  end

  def create
    @baby = @user.babies.new(baby_params.merge(hospital_id: @hospital.id))
    authorize @baby
    if @baby.save
      flash[:success] = "created successfully."
      redirect_to hospital_user_babies_path
    else
      flash[:alert] = @baby.errors.full_messages.join(' ,')
      initialize_risk_factor
      render 'new'
    end
  end	

  def show
    respond_to do |format|
      format.html
      format.csv { send_data @baby.import, filename: "Baby-#{Date.today}.csv"} 
    end
  end

  def edit
  end

  def update
    if @baby.update(baby_params)
      flash[:success] = "Update Successfully." 
      redirect_to  hospital_user_babies_path
    else
      flash[:alert] = @baby.errors.full_messages.join(' ,')
      render 'edit'
    end
  end

  def destroy
    flash[:alert] = "Destroy Successfully." if @baby.destroy
    redirect_to  hospital_user_babies_path
  end

  def send_email
    NotifierMailer.send_email(@baby).deliver_now
    flash.now[:success] = "Vaccinations details sent on email successfully."
  end

  def get_report_data
    babies = Baby.get_data
        
    res = [[" Severe stunted Height", babies.severe_stunted_height],["Severe under weight", babies.severe_under_weight],["Moderate under weight", babies.moderate_under_weight],["Normal weight", babies.normal_weight],["Possible overweight", babies.possible_overweight],["Weight for height", babies.weight_for_height],["Moderate stunted height", babies.moderate_stunted_height],["Normal", babies.normal],["Normal 2", babies.normal_2],["Possible very tall", babies.possible_very_tall]].map do |res_data|
      {
        type: "spline",
        dataPoints: res_data[1].push({x: 60, y: nil}),
        showInLegend: true,
        legendText: res_data[0]
     }
    end

    render json: res
  end

  private
    def set_baby
      @baby = Baby.where(hospital_id: @user.hospital_id).find(params[:id])
      authorize @baby
    end

    def set_user
      @hospital = Hospital.find(params[:hospital_id])
      @user = @hospital.users.find(params[:user_id])
    end

    def initialize_risk_factor
      RiskFactor.all.each { |risk_factor| @baby.baby_risk_factors.build(risk_factor_id: risk_factor.id) unless @baby.baby_risk_factors.map(&:risk_factor_id).include?(risk_factor.id)}
    end 
  
    def baby_params
      params.require(:baby).permit(:first_name, :place_of_birth, :middle_name, :last_name, :mode_of_delivery, :agpr_score, :head_circumference, :duration_of_labour, :avatar, :sex, :date_of_birth, :health_center, :physical_address, :hospital_id, mother_attributes: [:id, :first_name, :last_name, :physical_address, :phone_number, :email, :baby_id], father_attributes: [:id, :first_name, :last_name, :physical_address, :phone_number, :email, :baby_id], healths_attributes: [:id, :height, :weight], baby_risk_factors_attributes: [:id, :baby_id, :risk_factor_id])
    end
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_edit_form.html.haml
= bootstrap_form_for [@hospital, @user, @baby], local: true do |form|
  .row
    .col-sm-4
      = form.text_field :first_name,  placeholder:"First Name"
    .col-sm-4
      = form.text_field :middle_name, placeholder: "middle Name"
    .col-sm-4
      = form.text_field :last_name, placeholder: "last Name"
  .row
    .col-md-6
      = form.file_field  :avatar
    .col-md-6
      %br/
      = form.form_group :sex do
        = form.label :gender
        = form.radio_button :sex, "male", label: "Male", checked: true, inline: true
        = form.radio_button :sex, "female", label: "Female", inline: true
  .row
    - if @baby.new_record?
      .col-sm-4
        = form.date_field :date_of_birth, value: @baby.try(:date_of_birth)
    - if @baby.new_record?
      = form.fields_for :healths, @baby.healths.new do |health|
        .col-sm-4
          = health.text_field :weight,  placeholder: "Enter weight"
        .col-sm-4
          = health.text_field :height,  placeholder: "Enter height"
  .row
    .col-sm-4
      = form.number_field :agpr_score, min: 0
    .col-sm-4
      = form.number_field :duration_of_labour, min: 0, step: 0.5
    .col-sm-4
      = form.select :mode_of_delivery, options_for_select(["Normal", "C-section", "Forceps delivery", "Vacuum extraction", "Vaginal Birth After Cesarian"])
    .col-sm-4
      = form.number_field :head_circumference, min: 0, step: 0.5
    .col-sm-4
      = form.text_field :place_of_birth, placeholder: "Enter city of birth"

  %h4 Fillup  Mother Information
  .row
    = form.fields_for :mother, @baby.mother do |mother|
      .col-sm-6
        = mother.text_field :first_name,  placeholder: "Enter first name"
      .col-sm-6
        = mother.text_field :last_name,  placeholder: "Enter last name"
      .col-sm-6
        = mother.text_field :physical_address,  placeholder: "Enter your Address"
      .col-sm-6
        = mother.telephone_field :phone_number,  placeholder: "Enter your phone number"
      .col-sm-6
        = mother.email_field :email,  placeholder: "Enter email address"  
  %h4 Fillup  Father Information
  .row
    = form.fields_for :father, @baby.father do |father|
      .col-sm-6
        = father.text_field :first_name,  placeholder: "Enter first name"
      .col-sm-6
        = father.text_field :last_name,  placeholder: "Enter last name"
      .col-sm-6
        = father.text_field :physical_address,  placeholder: "Enter your Address"
      .col-sm-6
        = father.telephone_field :phone_number,  placeholder: "Enter your phone number"
      .col-sm-6
        = father.email_field :email,  placeholder: "Enter email address" 

  - if @baby.new_record?
    %h4 Select risk factors(optional)
    .row
      = form.fields_for :baby_risk_factors, form.object.baby_risk_factors.sort_by(&:risk_factor_id) do |baby_risk_factor|
        .col-sm-12
          = baby_risk_factor.check_box :risk_factor_id, {label: "#{baby_risk_factor.object.try(:risk_factor).try(:title)}", checked: !baby_risk_factor.object.new_record?}, baby_risk_factor.object.risk_factor_id
  .row
    .col-md-12
      = form.submit "submit", class: "btn btn-lg btn-success"

app/views/babies/_form.html.haml
= bootstrap_form_for [@hospital, @user, @baby], local: true do |form|
  .row
    .col-sm-4
      = form.text_field :first_name,  placeholder:"First Name"
    .col-sm-4
      = form.text_field :middle_name, placeholder: "middle Name"
    .col-sm-4
      = form.text_field :last_name, placeholder: "last Name"
  .row
    .col-md-6
      = form.file_field  :avatar
    .col-md-6
      %br/
      = form.form_group :sex do
        = form.label :gender
        = form.radio_button :sex, "male", label: "Male", checked: true, inline: true
        = form.radio_button :sex, "female", label: "Female", inline: true
  .row
    - if @baby.new_record?
      .col-sm-4
        = form.date_field :date_of_birth, value: @baby.try(:date_of_birth)
    - if @baby.new_record?
      = form.fields_for :healths, @baby.healths.new do |health|
        .col-sm-4
          = health.text_field :weight,  placeholder: "Enter weight"
        .col-sm-4
          = health.text_field :height,  placeholder: "Enter height"
  .row
    .col-sm-4
      = form.number_field :agpr_score, min: 0
    .col-sm-4
      = form.number_field :duration_of_labour, min: 0, step: 0.5
    .col-sm-4
      = form.select :mode_of_delivery, options_for_select(["Normal", "C-section", "Forceps delivery", "Vacuum extraction", "Vaginal Birth After Cesarian"])
    .col-sm-4
      = form.number_field :head_circumference, min: 0, step: 0.5
    .col-sm-4
      = form.text_field :place_of_birth, placeholder: "Enter city of birth"

  %h4 Fillup  Mother Information
  .row
    = form.fields_for :mother, @baby.build_mother do |mother|
      .col-sm-6
        = mother.text_field :first_name,  placeholder: "Enter first name"
      .col-sm-6
        = mother.text_field :last_name,  placeholder: "Enter last name"
      .col-sm-6
        = mother.text_field :physical_address,  placeholder: "Enter your Address"
      .col-sm-6
        = mother.telephone_field :phone_number,  placeholder: "Enter your phone number"
      .col-sm-6
        = mother.email_field :email,  placeholder: "Enter email address"  
  %h4 Fillup  Father Information
  .row
    = form.fields_for :father, @baby.build_father do |father|
      .col-sm-6
        = father.text_field :first_name,  placeholder: "Enter first name"
      .col-sm-6
        = father.text_field :last_name,  placeholder: "Enter last name"
      .col-sm-6
        = father.text_field :physical_address,  placeholder: "Enter your Address"
      .col-sm-6
        = father.telephone_field :phone_number,  placeholder: "Enter your phone number"
      .col-sm-6
        = father.email_field :email,  placeholder: "Enter email address" 

  - if @baby.new_record?
    %h4 Select risk factors(optional)
    .row
      = form.fields_for :baby_risk_factors, form.object.baby_risk_factors.sort_by(&:risk_factor_id) do |baby_risk_factor|
        .col-sm-12
          = baby_risk_factor.check_box :risk_factor_id, {label: "#{baby_risk_factor.object.try(:risk_factor).try(:title)}", checked: !baby_risk_factor.object.new_record?}, baby_risk_factor.object.risk_factor_id
  .row
    .col-md-12
      = form.submit "submit", class: "btn btn-lg btn-success"

app/views/babies/edit.html.haml
.pull-right
  = link_to "Back", hospital_user_babies_path, class: "btn btn-success"
.container
  .container.babysignup-container
    .col-md-12
      %h1 Update Baby Account
      %br/
      = render partial: "edit_form"
      %br
.container
  .container.vitamin-container
    .col-md-12
      %h1 Health Information
      .row
        .pull-right
          = link_to "Add Health info", new_hospital_user_baby_health_path(@hospital, @user, @baby), class: "btn btn-info"
      %br/
      %table.table.table-bordered
        %thead
          %tr
            %th age(in months)
            %th Height(cm)
            %th weight(Kg)
        %tbody
          - @baby.healths.each do |info|
            %tr
              %td= @baby.age_in_months
              %td= info.height
              %td= info.weight

app/views/babies/index.html.haml
.pull-right
  - unless current_user.admin?
    = link_to "New Baby Account", new_hospital_user_baby_path, class: "btn btn-success"     
.container
  .container.index-container
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2 Babies Table
        .ibox-content
          %table.table.table-bordered{style: "overflow-y: scroll;"}
            %thead
              %tr
                %th Name
                %th Date Of Birth
                %th Place Of Birth
                %th Gender
                %th Hospital name
                %th Action
            %tbody
              - @babies.each do |baby|
                %tr
                  %td= baby.first_name
                  %td= baby.date_of_birth
                  %td= baby.place_of_birth
                  %td= baby.sex
                  %td= baby.hospital.try(:name)
                  %td
                    - if current_user.nurse? || current_user.manager?
                      = link_to "", edit_hospital_user_baby_path(@hospital, @user, baby), class: "btn btn-default glyphicon glyphicon-edit"
                      = link_to "", hospital_user_baby_path(@hospital, @user, baby), class: "btn btn-default glyphicon glyphicon-eye-open"
                      = link_to "", hospital_user_baby_path(@hospital, @user, baby), method: :delete,data: { confirm: 'Are you sure?' }, class: "btn btn-default glyphicon glyphicon-trash"
                      = link_to "Infant Feeding", new_baby_baby_infant_feeding_path(baby), class: "btn btn-default"
                      = link_to "Care Form", new_baby_baby_care_path(baby), class: "btn btn-default"
                      = link_to "Improt Data",hospital_user_baby_path(@hospital, @user, baby, format: "csv"), class: "btn btn-default"
                      = link_to "Send Email",send_email_hospital_user_baby_path(@hospital, @user, baby), method: :post, remote: true, class: "btn btn-default"
                  
                    = link_to "height chart", height_baby_healths_path(baby), class: "btn btn-default"
                    = link_to "weight chart", weight_baby_healths_path(baby), class: "btn btn-default"
                 

app/views/babies/new.html.haml
.pull-right
  = link_to "Back", hospital_user_babies_path, class: "btn btn-success" 
%br
.container
  .container.babysignup-container
    %h1 Registration For New Baby
    %br
      = render partial: "form"